# This file was generated by Appraisal

source "https://rubygems.org"

gem "spree", "~> 3.2.0.rc1"
gem "spree_auth_devise", "~> 3.2.0.beta"
gem 'spree_gateway', '~> 3.2.0.beta'
gem "rails-controller-testing"
gem 'listen'

gem 'facebook-ads', path: "../facebook-ads"
gem 'sqlite3'
gem 'deface'
gem 'diffy'
gem 'rspec-activemodel-mocks'
gemspec
